name: Test FFMPEG download capabilities

on:
    workflow_dispatch:

jobs:
    run_script:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v4
            
            # Step 2: Set up Python environment
            - name: Set up Python 3.10
              uses: actions/setup-python@v5
              with:
                  python-version: '3.10'
            
            # Step 3: Install dependencies
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            
            # Step 4: Run the Python script
            - name: Run the script
              run: python testing.py

            # Step 5: Push test file into repository
            - name: Push into repo
              run: |
                git config --global user.name "not ZHD1987E"
                git config --global user.email "zhanghaodong101@outlook.com"

                git add "videos/test.mp4"
                git diff --quiet || git commit -m "Testing FFMPEG download capabilities"
                git push -f origin main
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}